sudo : required
services:
  - docker

before-install:
  - docker build -t harisht847/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true harisht847/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region:  "ap-south-1"
  app: "Docker-test"
  env: "DockerTest-env"
  bucket_name: "elasticbeanstalk-ap-south-1-209909805642"
  bucket_path: "Docker_test" 
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
